node {
    checkout scm
    load('ci/pipelines/microservicePipeline.groovy').runMicroservicePipeline([
        servicePath: 'backEnd/Microservices/Notification',
        imageName: 'notification'
    ])
}
