apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-uploads-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s/user-uploads
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-uploads-pvc
  namespace: smart-freelance
spec:
  storageClassName: manual
  volumeName: user-uploads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
