node {
    checkout scm
    load('ci/pipelines/microservicePipeline.groovy').runMicroservicePipeline([
        servicePath: 'backEnd/Microservices/aimodel-node',
        imageName: 'aimodel-node'
    ])
}
