node {
    checkout scm
    def runner = load('ci/pipelines/microservicePipeline.groovy')
    runner.runMicroservicePipeline([
    serviceName: 'aimodel-node',
    servicePath: 'backEnd/Microservices/aimodel-node',
    imageName: 'aimodel-node',
    deploymentName: '',
    repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
])
}
