node {
    checkout scm
    load('ci/pipelines/microservicePipeline.groovy').runMicroservicePipeline([
        servicePath: 'backEnd/Microservices/ticket-service',
        imageName: 'ticket-service'
    ])
}
