spring.application.name=AIMODEL
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

# JWT (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/smart-freelance}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWKS_URI:http://localhost:8080/realms/smart-freelance/protocol/openid-connect/certs}
