node {
    checkout scm
    def runner = load('ci/pipelines/microservicePipeline.groovy')
    runner.runMicroservicePipeline([
        serviceName: 'aimodel',
        servicePath: 'backEnd/Microservices/AImodel',
        imageName: 'aimodel',
        deploymentName: 'aimodel',
        repoUrl: 'https://github.com/YOUR_ORG/YOUR_REPO.git'
    ])
}
