node {
    checkout scm
    load('ci/pipelines/microservicePipeline.groovy').runMicroservicePipeline([
        servicePath: 'backEnd/Microservices/FreelanciaJob',
        imageName: 'freelancia-job'
    ])
}
